Name: teamDeLupus
IconPath: MyTeam.png
SoundPath: MyTeam.wav
Description: |
    Equipe de Lupus et XOXO (on test des trucs)
BrainsPackage: teamdeLupus
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarLight: WarLightBrainController
    WarHeavy: WarHeavyBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
